w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/config/routes.rb
Rails.application.routes.draw do
  # miscellaneous
  get "/"                     => 'welcome#index', as: 'root'
  get "/about"                => 'welcome#about', as: 'about'

  # artists
  get  "artists"              => 'artists#index', as: 'artists'
  get  "artists/new"          => 'artists#new', as: 'new_artist'
  post "artists"              => 'artists#create'
  get  "artists/:id"          => 'artists#show', as: 'artist'
  get  "artists/:id/edit"     => 'artists#edit', as: 'edit_artist'
  post  "artists/:id"         => 'artists#update'
  post "artists/:id/delete"   => 'artists#destroy', as: 'delete_artist'

  # songs
  get  "songs"              => 'songs#index', as: 'songs'
  get  "songs/new"          => 'songs#new', as: 'new_song'
  post "songs"              => 'songs#create'
  get  "songs/:id"          => 'songs#show', as: 'song'
  get  "songs/:id/edit"     => 'songs#edit', as: 'edit_song'
  post  "songs/:id"         => 'songs#update'
  post "songs/:id/delete"   => 'songs#destroy', as: 'delete_song'

  # playlists
  get  "playlists"                    => 'playlists#index', as: 'playlists'
  get  "playlists/new"                => 'playlists#new', as: 'new_playlist'
  post "playlists"                    => 'playlists#create'
  get  "playlists/:id"                => 'playlists#show', as: 'playlist'
  post "playlists/:id/add_song"       => 'playlists#add_song', as: 'add_song_to_playlist'
  post "playlists/:id/remove_song"    => 'playlists#remove_song', as: 'remove_song_from_playlist'
end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_and_belongs_to_many :songs
end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_and_belongs_to_many :playlists
end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
  end

  def create
    @artist = Artist.create!(params[:artist].permit!)
    redirect_to(artist_path(@artist))
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update!(params[:artist].permit!)
    redirect_to(artist_path(@artist))
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to(artists_path)
  end

end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end

  def new
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def create
    @playlist = Playlist.create!(params[:playlist])
    redirect_to("/playlists/#{@playlist.id}")
  end

  def add_song
    @playlist = Playlist.find(params[:id])
    @playlist.songs << Song.find(params[:song_id])
    redirect_to("/playlists/#{@playlist.id}")
  end

  def remove_song
    @playlist = Playlist.find(params[:id])
    @playlist.songs.delete(Song.find(params[:song_id]))
    redirect_to("/playlists/#{@playlist.id}")
  end

end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def new
  end

  def create
    @song = Song.create!(params[:song].permit!)
    redirect_to(song_path(@song))
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    @song.update!(params[:song].permit!)
    redirect_to(song_path(@song))
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to(songs_path)
  end

end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<form action="<%= artist_path(@artist) %>" method="post">
  <label for="artist[name]">Name:</label>
  <input name="artist[name]" value="<%= @artist.name %>">

  <label for="artist[photo_url]">Photo URL:</label>
  <input name="artist[photo_url]" value="<%= @artist.photo_url %>">

  <label for="artist[nationality]">Nationality:</label>
  <input name="artist[nationality]" value="<%= @artist.nationality %>">

  <input type="submit" value="Update">
</form>

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/views/artists/index.html.erb
<h2>Artists</h2>

<%= link_to('Add Artist', new_artist_path) %>

<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to(artist.name, artist_path(artist)) %>
    </li>
  <% end %>
</ul>

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/views/artists/new.html.erb
<h2>New Artist</h2>

<form action="<%= artists_path %>" method="post">
  <label>Name:</label>
  <input name="artist[name]">

  <label>Photo URL:</label>
  <input name="artist[photo_url]">

  <label>Nationality:</label>
  <input name="artist[nationality]">

  <input type="submit" value="Create">
</form>

<%= link_to('Back to Artists', artists_path) %>

w05/lesson_plans/d02b_rails_form_helpers/ex_tunr_rails/hamco_versions/starter/tunr/app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>
<h3><%= @artist.nationality %></h3>
<img src="<%= @artist.photo_url %>">

<ul>
  <% @artist.songs.each do |song| %>
    <li><%= song.title %></li>
  <% end %>
</ul>

<%= link_to('Edit', edit_artist_path(@artist)) %> |
<%= link_to('Back to Artists', artists_path) %> |
<form action="<%= delete_artist_path(@artist) %>" method="post">
  <input type="submit" value="Delete Artist">
</form>